### ISSUE TITLE
Package dbt-athena/athena_utils was not found in the package index

### ISSUE THREAD

**Issue by wtfzambo** [lalalilo/athena-utils#17]
If installing the package with:

```yml
packages:
  - package: dbt-athena/athena_utils
    version: 0.5.0
```

it won't work, with the error message same as the title. However, `lalalilo/athena_utils` will work.
